-- SCRIPT DE CONFIGURAÇÃO COMPLETA DO SUPABASE
-- Execute este script no SQL Editor do seu projeto Supabase para criar todas as tabelas necessárias.

-- 1. Tabela de Serviços
CREATE TABLE IF NOT EXISTS services (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  duration INTEGER NOT NULL,
  price NUMERIC NOT NULL,
  icon TEXT,
  description TEXT,
  includes TEXT[],
  image TEXT,
  category TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tabela de Profissionais
CREATE TABLE IF NOT EXISTS professionals (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL,
  role TEXT NOT NULL,
  initials TEXT,
  email TEXT UNIQUE,
  password TEXT,
  photo TEXT,
  bio TEXT,
  specialties TEXT[],
  show_in_vitrine BOOLEAN DEFAULT TRUE,
  cpf TEXT UNIQUE,
  dob DATE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Tabela de Clientes
CREATE TABLE IF NOT EXISTS clients (
  cpf TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT,
  phone TEXT,
  password TEXT,
  cep TEXT,
  street TEXT,
  number TEXT,
  complement TEXT,
  neighborhood TEXT,
  city TEXT,
  state TEXT,
  dob DATE,
  gender TEXT,
  children TEXT,
  profession TEXT,
  photo TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Tabela de Agendamentos
CREATE TABLE IF NOT EXISTS appointments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  phone TEXT NOT NULL,
  email TEXT,
  service_id BIGINT REFERENCES services(id),
  date DATE NOT NULL,
  time TEXT NOT NULL,
  status TEXT DEFAULT 'pending',
  prof_name TEXT,
  prof_id UUID REFERENCES professionals(id),
  paid BOOLEAN DEFAULT FALSE,
  discount NUMERIC DEFAULT 0,
  final_price NUMERIC,
  client_id TEXT, -- Pode ser CPF ou Telefone
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Tabela de Avaliações
CREATE TABLE IF NOT EXISTS reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_cpf TEXT REFERENCES clients(cpf),
  client_name TEXT,
  service_id BIGINT REFERENCES services(id),
  stars INTEGER CHECK (stars >= 1 AND stars <= 5),
  comment TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Tabela de Carrossel (Vitrine)
CREATE TABLE IF NOT EXISTS carousel_slides (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  image TEXT NOT NULL,
  title TEXT,
  subtitle TEXT,
  "order" INTEGER DEFAULT 0,
  title_color TEXT DEFAULT '#ffffff',
  title_align TEXT DEFAULT 'center',
  title_font TEXT DEFAULT 'sans',
  discount_badge_text TEXT,
  show_discount_badge BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Tabela de FAQ
CREATE TABLE IF NOT EXISTS faqs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  q TEXT NOT NULL,
  a TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. Tabela de Horários de Funcionamento
CREATE TABLE IF NOT EXISTS working_hours (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  day_of_week INTEGER UNIQUE NOT NULL, -- 0 (Domingo) a 6 (Sábado)
  start_time TEXT NOT NULL,
  end_time TEXT NOT NULL,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. Tabela de Configurações (Tema, Cores, etc)
CREATE TABLE IF NOT EXISTS settings (
  key TEXT PRIMARY KEY,
  value JSONB,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- CONFIGURAÇÃO DE SEGURANÇA (RLS)
-- Para simplificar o desenvolvimento, vamos habilitar acesso total. 
-- Em produção, você deve restringir estas políticas.

ALTER TABLE services ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Acesso Público" ON services FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE professionals ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Acesso Público" ON professionals FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE clients ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Acesso Público" ON clients FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE appointments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Acesso Público" ON appointments FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE reviews ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Acesso Público" ON reviews FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE carousel_slides ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Acesso Público" ON carousel_slides FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE faqs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Acesso Público" ON faqs FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE working_hours ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Acesso Público" ON working_hours FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Acesso Público" ON settings FOR ALL USING (true) WITH CHECK (true);

-- Inserir horários padrão se a tabela estiver vazia
INSERT INTO working_hours (day_of_week, start_time, end_time, is_active)
VALUES 
  (1, '08:00', '18:00', true),
  (2, '08:00', '18:00', true),
  (3, '08:00', '18:00', true),
  (4, '08:00', '18:00', true),
  (5, '08:00', '18:00', true),
  (6, '08:00', '12:00', true)
ON CONFLICT (day_of_week) DO NOTHING;

-- Inserir configurações padrão
INSERT INTO settings (key, value)
VALUES 
  ('accent_color', '"#fbbf24"'),
  ('theme', '"dark"')
ON CONFLICT (key) DO NOTHING;
